### ISSUE TITLE
Chrome 에서 스크롤시 repaint 가 안일어나는 문제

### ISSUE THREAD

**Issue by imazine** [tipJS-Team/tipJS#4]
소개 페이지에서 앵커태그를 클릭하여 스크롤 할 때 스크롤 범위가 크면 레이아웃이 덜 그려집니다.

현재로서는 Chrome 버그로 보여지며

JavaScript로 강제로 repaint를 일으키거나 브라우저 업데이트를 기다리는 방법 중 골라야 합니다.

**Comment by tipjs** [comment]
뭐에대한 버근지도 적어야지. tipJS 말하는거냐 아니면 뭐 말하는거야?  이 이슈 지우고 다시 써
